### ISSUE TITLE
TS definitions emits errors during `yarn install` for a typescript project

### ISSUE THREAD

**Issue by mattbishop** [kriszyp/msgpackr#10]
When using yarn to add Msgpackr as a dependency, it will emit these error messages:

yarn run v1.22.10
$ tsc
../node_modules/msgpackr/index.d.ts(8,2): error TS7010: 'write', which lacks return-type annotation, implicitly has an 'any' return type.
../node_modules/msgpackr/index.d.ts(8,8): error TS7006: Parameter 'value' implicitly has an 'any' type.
../node_modules/msgpackr/index.d.ts(9,2): error TS7010: 'end', which lacks return-type annotation, implicitly has an 'any' return type.
../node_modules/msgpackr/index.d.ts(9,6): error TS7006: Parameter 'value' implicitly has an 'any' type.
../node_modules/msgpackr/unpack.d.ts(31,17): error TS7010: 'addExtension', which lacks return-type annotation, implicitly has an 'any' return type.
error Command failed with exit code 2.

Should be a matter of adding more type declarations to the definitions.

**Comment by mattbishop** [comment]
When using the submodules, tsc produces these errors:

node_modules/msgpackr/unpack.d.ts:2:26 - error TS2304: Cannot find name 'ALWAYS'.

2  useFloat32?: 0 | typeof ALWAYS | typeof DECIMAL_ROUND | typeof DECIMAL_FIT
                           ~~~~~~

node_modules/msgpackr/unpack.d.ts:2:42 - error TS2304: Cannot find name 'DECIMAL_ROUND'.

2  useFloat32?: 0 | typeof ALWAYS | typeof DECIMAL_ROUND | typeof DECIMAL_FIT
                                           ~~~~~~~~~~~~~

node_modules/msgpackr/unpack.d.ts:2:65 - error TS2304: Cannot find name 'DECIMAL_FIT'.

2  useFloat32?: 0 | typeof ALWAYS | typeof DECIMAL_ROUND | typeof DECIMAL_FIT
                                                                  ~~~~~~~~~~~

node_modules/msgpackr/unpack.d.ts:28:17 - error TS7010: 'addExtension', which lacks return-type annotation, implicitly has an 'any' return type.

28 export function addExtension(extension: Extension)
                   ~~~~~~~~~~~~

**Comment by kriszyp** [comment]
Ok, updated in 1.2.0.

**Comment by mattbishop** [comment]
I found another problem in a different project, trying to figure it out.

**Comment by mattbishop** [comment]
The issue with ENUMs is that msgpackr isn't compiled by ts to generate the enum in JS space, so the data also has to be in the JS code. I'll submit another PR to fix.

**Comment by mattbishop** [comment]
This is what Typescript emits for the enum:

```javascript
var FLOAT32_OPTIONS;
(function (FLOAT32_OPTIONS) {
    FLOAT32_OPTIONS[FLOAT32_OPTIONS["NEVER"] = 0] = "NEVER";
    FLOAT32_OPTIONS[FLOAT32_OPTIONS["ALWAYS"] = 1] = "ALWAYS";
    FLOAT32_OPTIONS[FLOAT32_OPTIONS["DECIMAL_ROUND"] = 3] = "DECIMAL_ROUND";
    FLOAT32_OPTIONS[FLOAT32_OPTIONS["DECIMAL_FIT"] = 4] = "DECIMAL_FIT";
})(FLOAT32_OPTIONS = exports.FLOAT32_OPTIONS || (exports.FLOAT32_OPTIONS = {}));
```

**Comment by kriszyp** [comment]
Has this enum/type-definition been adequately addressed, or do you think there are still changes that are needed?

**Comment by mattbishop** [comment]
It is working well for me now so I think we can close it.
