### ISSUE TITLE
Upgrade from other msgpack libs - map and set

### ISSUE THREAD

**Issue by gonenduk-dy** [kriszyp/msgpackr#103]
Hi,

Since msgpack is a well defined standard, replacing a msgpack lib with another should be an easy task - as long as the result of pack and unpack produce the same results. Sometimes, a project is made of several different stacks and languages - each with its own msgpack lib, but as long as pack and unpack produce the same results - the move to a new lib is transparent.
With msgpackr we can this by disabling some great features ot make it faster and more compact.
However, when dealing with types that are not defined in the standard, like map or set, each library has its own way of dealing with them. In msgpackr we can choose between keeping the original type or translating them to object/array.
In some older libs, like msgpack-node - which was the most popular 4 years ago, the lib ignores those types and simply replaces them with an empty object.

Can we have a flag to do the same and replace map and set with an empty object - so we will be able to replace msgpack-node (or any other lib which does the same) with this lib?

Thanks!

**Comment by gonenduk-dy** [comment]
hey @kriszyp 
The commit looks good!
When can we have it published to npm?

**Comment by kriszyp** [comment]
Ok, I published this v1.9.0.

**Comment by gonenduk-dy** [comment]
Hi again,

I am trying to check the new 1.9 version (on node 14.18 - so the old package can work too) and I get a reference to null exception.
Can you verify it is working for you?

Thanks!

`
const msgpack = require('msgpack');
const { Packr } = require('msgpackr');
const msgpackr = new Packr({ useRecords: false, encodeUndefinedAsNil: true, variableMapSize: true, mapAsEmptyObject: true, setAsEmptyObject: true  });

const map = new Map();
map.set('a', 1);
map.set('b', 2);
const set = new Set();
set.add('a');
set.add('b');
const input = { set };

const packed = msgpackr.pack(input);
const old_packed = msgpack.pack(input);

console.log(Buffer.compare(packed, old_packed) ? 'non identical' : 'identical');
console.log(packed.toString('base64'));
console.log(old_packed.toString('base64'));
`
