### ISSUE TITLE
setAsEmptyObject - null Exception

### ISSUE THREAD

**Issue by gonenduk-dy** [kriszyp/msgpackr#107]
Hi @kriszyp ,

I am running the test code attached below on Node.js 18.16 with msgpackr 1.9 using the 2 new flags and get this error:
```
TypeError: Cannot set properties of null (setting '10')
    at Packr.writeObject.useRecords.variableMapSize.target.<computed> (/Users/.../node_modules/msgpackr/dist/node.cjs:1683:24)
```

When turning off the 2 flags, it works well.

Thanks,
Gonen.

The test code:
```
const { Packr } = require('msgpackr');
const msgpackr = new Packr({ useRecords: false, encodeUndefinedAsNil: true, variableMapSize: true, mapAsEmptyObject: true, setAsEmptyObject: true  });

const map = new Map();
map.set('a', 1);
map.set('b', 2);
const set = new Set();
set.add('a');
set.add('b');
const input = { map, set };

const packed = msgpackr.pack(input);
const unpacked = msgpackr.unpack(packed);
console.log(JSON.stringify(unpacked));
```

**Comment by gonenduk-dy** [comment]
@kriszyp 
Any update?

**Comment by kriszyp** [comment]
Yes, and I don't know why github isn't properly showing it, looks linked to me, but added a test for this here https://github.com/kriszyp/msgpackr/commit/ab6dcc49b888c863af394453090a5d127f22148a, and it doesn't seem to reproduce for me. I am doing something wrong?

**Comment by gonenduk-dy** [comment]
hey @kriszyp .

I cloned your repo and ran npm test, using node 18.16. Also for me, the tests pass, including the one for the map and set as object.
However, when I do a clean fresh project and use the code above - i get an exception.
By the way, the issue is not with map but only with set (also with an empty set).

To reproduce, create a new project with:
```
mkdir test
cd test
npm init
npm install msgpackr@1.9.0
touch index.js
```

Put this into index.js:
```
const { Packr } = require('msgpackr');
const packr = new Packr({ useRecords: false, encodeUndefinedAsNil: true, variableMapSize: true, mapAsEmptyObject: true, setAsEmptyObject: true });

const set = new Set();
set.add('a');
const input = { set };

const packed = packr.pack(input);
const unpacked = packr.unpack(packed);
```

And run with:
```
node index.js
```

You should get the exception.

**Comment by gonenduk-dy** [comment]
Cool Thanks!

Verified the new version and it does solve the issue.
Closing the issue.

Thanks again!
Appreciate your huge effort and quick response.

P.S. Will continue to test backward compatibility. If we find anything - will let you know in yet another issue :)
