### ISSUE TITLE
Error when trying to unpackMultiple with incomplete buffer

### ISSUE THREAD

**Issue by somebee** [kriszyp/msgpackr#109]
I'm parsing a binary response in the browser, trying to unpack each chunk as it is read. Since `UnpackrStream` is not supported on the browser I'm rolling my own version which catches errors from unpackMultiple, keeping the failed chunk and prepending it when reading the next chunk (much like UnpackrStream does internally).

This works fine for most cases. But, if a chunk doesn't even fit a single object (ie, we receive a 200 byte chunk in the browser, but the packed object is 240 bytes), msgpackr seems to lose it's state and subsequent parsing becomes incorrect. I'll try to make a failing test but wanted to file it immediately in case you know about it or immediately understand the case.

It only happens when the chunk contains less than one whole unpackable object. For all other cases it works fine to catch errors, look at lastPosition, and concat chunks etc. When streaming from a Response in the browser we cannot control how many bytes we get per chunk. For now I had to instead wait for the whole array-buffer and use unpackMultiple in one go.

**Comment by kriszyp** [comment]
I don't immediately have an idea of what is wrong. It is the intent of https://github.com/kriszyp/msgpackr/blob/master/tests/test-incomplete.js to try to test for these scenarios of incomplete chunks. Maybe that test is missing some scenarios? Anyway, certainly will take a look if you come up with reproductions.

**Comment by somebee** [comment]
Yeah I will try to make a test-case this week!

**Comment by somebee** [comment]
Here's the most compact reproduction I could come up with: https://scrimba.com/scrim/cpGa4ku3

Fwiw, it works if I force it to add restoreStructures in recordDefinition:

```js
const recordDefinition = (id, highByte) => {
	let structure = read().map(property => property.toString()) // ensure that all keys are strings and that the array is mutable
	let firstByte = id
	if (highByte !== undefined) {
		id = id < 32 ? -((highByte << 5) + id) : ((highByte << 5) + id)
		structure.highByte = highByte
	}
	let existingStructure = currentStructures[id]
	if (existingStructure) { //  COMMENTED OUT: && existingStructure.isShared
		(currentStructures.restoreStructures || (currentStructures.restoreStructures = []))[id] = existingStructure
	}
	currentStructures[id] = structure
	structure.read = createStructureReader(structure, firstByte)
	return structure.read()
}
```

**Comment by somebee** [comment]
Thank you for fixing it so quickly!
