### ISSUE TITLE
is it thread safe when use threads_worker

### ISSUE THREAD

**Issue by introspection3** [kriszyp/msgpackr#121]
is it thread safe when use threads_worker

**Comment by kriszyp** [comment]
Yes, it is safe to use with worker_threads.

**Comment by introspection3** [comment]
> Yes, it is safe to use with worker_threads.

can we use it async??

**Comment by kriszyp** [comment]
You can use msgpackr with asynchronous code. The msgpackr functions themselves do not have asynchronous APIs, they immediately execute, and there is no meaningful off-thread work that they can do asynchronously.
