### ISSUE TITLE
packing a `function` returns the same as packing `undefined`

### ISSUE THREAD

**Issue by Nokel81** [kriszyp/msgpackr#134]
**Description:**

If I run the following code

```ts
import { Packr } from "msgpackr";

const packer = new Packr({
  moreTypes: true,
});

const data = packer.unpack(packer.pack(() => 10));

console.log(data); // undefined
```

I would have expected that it should throw, or at least give me the option to have it throw

**Comment by kriszyp** [comment]
This is available with the `writeFunction` option. Added this to the docs.

**Comment by Nokel81** [comment]
Ah excellent, thanks!
