### ISSUE TITLE
Options types to Packr and Unpackr not complete

### ISSUE THREAD

**Issue by diogosantosmendes** [kriszyp/msgpackr#2]
interface Options {
	useFloat32: number
}

For the ones that uses typescript (as me) and tries to unpack as JS Object you need to define in the types file (index.d.ts) that option, as well as the other ones refered in documentation (useRecords, structures, structuredClone, variableMapSize, copyBuffers, useTimestamp32)

**Comment by kriszyp** [comment]
Thanks for reporting, published fix in 0.5.3. Let me know if you see any other missing types.
