### ISSUE TITLE
add support for deno ?

### ISSUE THREAD

**Issue by gcxfd** [kriszyp/msgpackr#25]
[deno](https://deno.land/) is very good ,  can I use msgpackr in deno ?

**Comment by kriszyp** [comment]
This seems like a good idea. It is worth noting that deno doesn't have support for native modules, so the performance boost from msgpackr-extract wouldn't be available. But, I still could change the modules to be ESM modules (especially since Node 10 is EOL now), so they would work in Deno.

**Comment by gcxfd** [comment]
https://deno.land/manual/getting_started/webassembly
https://www.secondstate.io/articles/deno-webassembly-rust-wasi/
if need speed , deno can use rust & webassembly , but I think ESM modules is enough for use

**Comment by kriszyp** [comment]
Yes, I am working on it!

**Comment by kriszyp** [comment]
I have fully upgraded msgpackr to using ESM format for all modules now, so all the modules (at least the ones that aren't specific to node streams) should be available for use in Deno (you could reference through standard git protocol):
https://raw.githubusercontent.com/kriszyp/msgpackr/master/index.js

**Comment by gcxfd** [comment]
thanks , you can publish it to deno.land , so more deno user can find it

https://deno.land/x

see image below

![image](https://user-images.githubusercontent.com/69608605/118217733-a6bf6a80-b4a8-11eb-9d72-a5406d8ea09b.png)

**Comment by kriszyp** [comment]
ok, published it, thank you!
