### ISSUE TITLE
Another buffers problem

### ISSUE THREAD

**Issue by maxless** [kriszyp/msgpackr#26]
Hello again :)

I've found another problem with buffers. The following message (I've had to save it as JSON, then load it and convert the array into Haxe list to trigger the bug, looks like it's related to extensions) results in this:
```
/home/hexen/node_modules/msgpackr/pack.js:719
        target.set(result, position)
               ^

RangeError: offset is out of bounds
    at Buffer.set (<anonymous>)
    at writeExtensionData (/home/hexen/node_modules/msgpackr/pack.js:719:9)
    at pack (/home/hexen/node_modules/msgpackr/pack.js:361:21)
    at Packr.writeObject (/home/hexen/node_modules/msgpackr/pack.js:523:5)
    at pack (/home/hexen/node_modules/msgpackr/pack.js:295:7)
    at Packr.pack.encode (/home/hexen/node_modules/msgpackr/pack.js:103:5)
    at Main.run (/home/hexen/test/nodejs18-msgpack-bug3/main.js:46:14)
    at Function.main (/home/hexen/test/nodejs18-msgpack-bug3/main.js:53:5)
    at /home/hexen/test/nodejs18-msgpack-bug3/main.js:140:6
    at Object.<anonymous> (/home/hexen/test/nodejs18-msgpack-bug3/main.js:141:3)
```

I've tried to remove everything irrelevant but it looks like the array sizes and number of object fields matters. That was the smallest message I could produce.

[main.txt](https://github.com/kriszyp/msgpackr/files/6458939/main.txt)
[json.txt](https://github.com/kriszyp/msgpackr/files/6458940/json.txt)

**Comment by maxless** [comment]
Great! I've another problem - is there a way to serialize the given class instance as one of the basic classes, in this case an array without making it an extension type? That would help me with message handling on the receiving end.

**Comment by kriszyp** [comment]
This should be addressed with the new read and write functions for extensions, if you want to give that a try?

**Comment by maxless** [comment]
I'm sorry, it looks like you misunderstood. Looking at your code:
```
if (extension.write) {
  target[position++] = 0xd4 // one byte "tag" extension
  target[position++] = extension.type
  target[position++] = 0
  pack(extension.write.call(this, value))
  return
}
```
It will still use a d4 extension byte using the extension system. What I had in mind is save the custom class instance as one of the base types bypassing that. I did a hack like this (in the same spot in the code):
```
if (extension.type == 10) {
  let len = value.length
  target[position++] = 0xdc
  target[position++] = len >> 8
  target[position++] = len & 0xff
  let _g_head = value.h;
  while(_g_head != null) {
    let val = _g_head.item;
    _g_head = _g_head.next;
    pack(val);
  }
  return;
}
```
This way the Haxe list becomes a basic msgpack array. I realize that this might be a rare use-case so feel free to not implement anything to handle it.

**Comment by kriszyp** [comment]
So if I understand correctly, you don't want to use the msgpack extension encoding at all (you don't want to actually serialize the type `10`), you just want a custom encoding function for your class, right? Perhaps we could allow extensions to not specify a type, and just specify a write function (and Class), then you write function could just convert a Haxe list to an array to be serialized? And I assume this doesn't round-trip, there is no distinction for these arrays and no deserialization/read process for converting the array back to a list, right?

**Comment by maxless** [comment]
Yes, that's correct. I want to bypass the msgpack extension system for a specific array-like class that I'm fine with reading them as arrays if sent from the other side.

**Comment by kriszyp** [comment]
As of v1.3.4, if you specify an extension (with write) with no type, it should be encoded without the msgpack extension encoding (and will be decoded just with the data you provided by write).

**Comment by maxless** [comment]
Seems to work as intended, thanks!
