### ISSUE TITLE
Feature request: Option to pack undefined as msgpack nulls

### ISSUE THREAD

**Issue by maxless** [kriszyp/msgpackr#28]
Currently undefineds are packed as 0xd4 + 0x0 which means that you cannot unpack it on another platform without adding an extension. Since in our case these platforms only have nulls, this seems to be the best solution.

**Comment by kriszyp** [comment]
Makes sense. I added an `encodeUndefinedAsNil` option for this. Published in v1.3.3

**Comment by maxless** [comment]
Thanks for your quick work!
