### ISSUE TITLE
Strategy for dealing with file system errors

### ISSUE THREAD

**Issue by beaugunderson** [kriszyp/msgpackr#29]
I got an error while using a `PackrStream`:

```
node:events:342
      throw er; // Unhandled 'error' event
      ^

Error: EINVAL: invalid argument, write
Emitted 'error' event on WriteStream instance at:
    at WriteStream.onerror (node:internal/streams/readable:770:14)
    at WriteStream.emit (node:events:365:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'write'
}
```

And the resulting file ended up as 0 bytes.

This is my `writePacked` function:

```
exports.writePacked = (path, data) => {
  const messageStream = new PackrStream();
  const file = fs.createWriteStream(path);

  messageStream.pipe(file);
  messageStream.write(data);

  file.close();
};
```

It may be a coincidence, but I had probably just crossed ~1.4gb of data in the file. My setup here reads in the file, adds some additional data to it from an external API, then saves it again, so that it grows with each run.

I'm curious if there are any size limitations I should worry about, or if this was just a freak filesystem issue.

Instead of writing to the same file I guess I'll have to implement a temporary file and an atomic move if successful, so that I remove the danger of an error wiping out my data. :)

**Comment by kriszyp** [comment]
NodeJS buffer's have an upper limit of 4GB. I am not aware of any limits on writing to a file (https://linux.die.net/man/3/pwrite only mentions invalid argument with negative offsets).

> Instead of writing to the same file I guess I'll have to implement a temporary file and an atomic move if successful, so that I remove the danger of an error wiping out my data.

I think that is a good idea anyway, to protect against corruption if there is a crash during the operation as well.

Is there anything else you think msgpackr could do for this situation?

**Comment by beaugunderson** [comment]
Makes sense to me, and I don't think msgpackr needs to do anything else in this situation, but I've now run up against another issue (happy to open a new issue for it if you'd like); in short the promise-based stream functions don't seem to work with msgpackr:

```js
exports.writePacked = async function writePacked(path, data) {
  const name = tmpNameSync();

  console.log(`Writing packed data to ${path}...`);
  const messageStream = new PackrStream();

  console.log(`Creating write stream for temporary file '${name}'`);
  const fileStream = fs.createWriteStream(name);

  messageStream.pipe(fileStream);

  console.log('Writing data...');
  messageStream.write(data);

  messageStream.end();

  console.log('Awaiting `finished` event...');
  // process exits here with 0 exit code!
  await finished(messageStream);

  console.log('Closing file...');
  fileStream.close();

  console.log(`Moving '${name}' to '${path}'...`);
  fsExtra.moveSync(name, path, { overwrite: true });
};
```

```
Writing packed data to ./data/test.msgpack...
Creating write stream for temporary file '/var/folders/_0/trky75w11wgf02hthgmkcj7r0000gn/T/tmp-67175-SU5RxRo8GGDX'
Writing data...
Awaiting `finished` event...
```

**Comment by beaugunderson** [comment]
Gave up on that because the stream approach was providing no benefit with one write; just switched to using `fs.writeFileSync(path, pack(data))` :)

(But I do think there is something broken in the Transform implementation... I see the tests just rely on a setTimeout rather than waiting for the `finished` event)

**Comment by kriszyp** [comment]
Ok, I think it should be fixed with the above commit (can also be worked around by setting using {writable: false} in finished).
