### ISSUE TITLE
Fixarray?

### ISSUE THREAD

**Issue by smolck** [kriszyp/msgpackr#3]
Hello! I apologize if this is a dumb question, but does this library handle `fixarray`s? I was looking through the code and I couldn't find any code that appeared to handle them.

I'm asking because I'd like to use this library in a project I've been working on, but I get deserialization results after swapping to it from [another implementation](https://github.com/smolck/uivonim/blob/5d00ed52d49989031c7cfe0bfa766db56ebedd41/src/messaging/msgpack-decoder.ts#L103), and I'm trying to figure out what's causing that difference; it may be specific to that project, but I'm not sure, so I figured I'd verify that everything is being decoded as I think.

Thanks!

**Comment by smolck** [comment]
Edit: sorry for the spam, I should've investigated further before creating this issue; appears to be due to my misunderstanding of how `addExtension` works.

**Comment by kriszyp** [comment]
Ok, well, let me know if there is anything that would improve interoperability.

**Comment by smolck** [comment]
@kriszyp Will do! I think I have a better understanding of what I'm trying to do now, but I'm still kind of confused about extensions, so here's my question (again, I apologize for the lack of a clear issue!):

The msgpack spec has this:
```
fixext 1 stores an integer and a byte array whose length is 1 byte
+--------+--------+--------+
|  0xd4  |  type  |  data  |
+--------+--------+--------+
```

When I use `addExtension` to create a type, how can I get `type` *and* data? I've tried:
```javascript
addExtension({
  type: 1,
  unpack(buffer) {
    // do stuff with buffer and return
  }
})
```
but `buffer` seems to only have `data`, not `type`. What am I missing?

**Comment by kriszyp** [comment]
I would have assumed if your code knows the type when creating the extension, it would still have access to the type when unpack is called, either by closure, or you could bind a type argument to unpack function:
```
const type = 1;
addExtension({ type, unpack: myUnpack.bind(null, type) })
```

However, if it would help, I could pass in the type in as the second argument to the custom unpack function.

**Comment by smolck** [comment]
Ah, yes, that is correct; I was misunderstanding the purpose of the `type` argument. Part of that was because the README says the extension type code should be a number from 1-100, but in my case `0` is a type code, so maybe that should be changed?

Also, I've managed to get things working! Thanks for your help!

**Comment by kriszyp** [comment]
The reason for using 1-100 for extension is because there are other library(s) that use the type code of `0` to represent `undefined`, and msgpackr follows that pattern.
