### ISSUE TITLE
Error using package in browser

### ISSUE THREAD

**Issue by bobsingor** [kriszyp/msgpackr#30]
I'm trying to import msgpackr in a webpack browser project.

I'm getting the following error: 
ERROR in ./packages/core/src/components/app/index.tsx 17:19-38
Module not found: Error: Package path . is not exported from package /Users/bobsingor/Github/cloudpdf-viewer/node_modules/msgpackr (see exports field in /Users/bobsingor/Github/cloudpdf-viewer/node_modules/msgpackr/package.json)
 @ ./packages/core/src/app.tsx 15:30-57

Can somebody help me with this?

**Comment by kriszyp** [comment]
Pushed a fix, and published in v1.3.6, did you want to give that a try?

**Comment by bobsingor** [comment]
@kriszyp Thanks for looking into this. I upgraded to 1.3.6 and still get the same error.

**Comment by kriszyp** [comment]
Just to be sure, did you restart webpack? I noticed webpack seemed to cache my package.json, and had to restart to get it working. And I assume you are importing with something like `import { unpack } from 'msgpackr'`?

And btw, as a workaround (although I certainly like to figure out how to fix it), might also try to import `'msgpackr/pack'` or `'msgpackr/unpack'` (which is preferred so that you are only loading the modules you need.

**Comment by bobsingor** [comment]
@kriszyp Yes I did restart webpack. Let me see if I can reproduce the issue in codesandbox

**Comment by bobsingor** [comment]
also by using `import { unpack } from 'msgpackr/unpack'` i'm getting the following error:

`ERROR in ./packages/core/src/components/app/index.tsx 17:17-43
Module not found: Error: Package path ./unpack is not exported from package /Users/bobsingor/Github/cloudpdf-viewer/node_modules/msgpackr (see exports field in /Users/bobsingor/Github/cloudpdf-viewer/node_modules/msgpackr/package.json)`

**Comment by bobsingor** [comment]
@kriszyp It took some time but I reproduced the issue in codesandbox.

it turns out that it only happens while using workspaces. You can see in the codesandbox that it does not matter if you import `msgpackr/unpack` or `msgpackr` in both situations it gives this error.

[Reproduction in codesandbox](https://codesandbox.io/s/wizardly-moser-v7eo9?file=/packages/test/src/index.tsx)

**Comment by kriszyp** [comment]
Thank you for the great test case! Should be fixed in v1.3.7 now (simplifying the exports seems to help to not confuse webpack).

**Comment by bobsingor** [comment]
@kriszyp This is great! You are the best! Thanks for your help
