### ISSUE TITLE
PackrStream does not have the correct typing to .pipe()

### ISSUE THREAD

**Issue by bobsingor** [kriszyp/msgpackr#31]
I am using msgpackr in a TypeScript project.

This is my code:
```javascript
const writeStream = fs.createWriteStream(`file.msp`);
const encodeStream = new PackrStream();
encodeStream.pipe(writeStream);
```

Getting the following error:
`TypeScript error: Property 'pipe' does not exist on type 'PackrStream'.`

Can you add the pipe property to the type PackrStream?

**Comment by bobsingor** [comment]
@kriszyp thanks for the commit. Can you release this on NPM?

**Comment by bobsingor** [comment]
@kriszyp Also the types are missing for the options on the constructor for both PackrStream and UnpackrStream

**Comment by bobsingor** [comment]
@kriszyp The stream does not write anything to the file. Please check out this example:
https://codesandbox.io/s/node-js-msgpackr-stream-forked-wusio?file=/src/index.js

Am I doing something wrong here?

**Comment by kriszyp** [comment]
> Also the types are missing for the options on the constructor for both PackrStream and UnpackrStream

It seems like the constructor types are properly being inherited from Transform for me. That isn't working for you?

> @kriszyp The stream does not write anything to the file. Please check out this example:
> https://codesandbox.io/s/node-js-msgpackr-stream-forked-wusio?file=/src/index.js

When I run the streaming/writing part of your code, it seems to properly write to the file. Perhaps this is a timing issue of checking the file before the write finishes? You can explicitly end the stream and await for its completion like in the unit test:
https://github.com/kriszyp/msgpackr/blob/master/tests/test-node-stream.js#L66

>  Can you release this on NPM?

The previous fix is now published v1.3.8

**Comment by bobsingor** [comment]
> @kriszyp Also the types are missing for the options on the constructor for both PackrStream and UnpackrStream

I'm expecting to be able to add these options on the PackrStream constructor:
```typescript
interface Options {
	useFloat32?: FLOAT32_OPTIONS
	useRecords?: boolean
	structures?: {}[]
	structuredClone?: boolean
	mapsAsObjects?: boolean
	variableMapSize?: boolean
	copyBuffers?: boolean
	useTimestamp32?: boolean
	largeBigIntToFloat?: boolean
	encodeUndefinedAsNil?: boolean
	getStructures?(): {}[]
	saveStructures?(structures: {}[]): boolean | void
}
```

**Comment by bobsingor** [comment]
> When I run the streaming/writing part of your code, it seems to properly write to the file. Perhaps this is a timing issue of checking the file before the write finishes? You can explicitly end the stream and await for its completion like in the unit test:
> https://github.com/kriszyp/msgpackr/blob/master/tests/test-node-stream.js#L66

Check out this codesandbox. The file generated is empty. In my node environment nothing is being written to the file. How are you testing it? what node version? your code? I tried different node versions but exactly the same code as in your tests fail for me and seem to fail in the codesandbox
https://codesandbox.io/s/node-js-msgpackr-stream-forked-x296n?file=/src/index.js

**Comment by bobsingor** [comment]
@kriszyp Ok I found out that it's only working in node 15+

**Comment by kriszyp** [comment]
Ok, sorry for missing those, and thank you for the clue about the node version. Fixes for typings and stream methods should be in v1.3.9.
