### ISSUE TITLE
Automatically infer structures

### ISSUE THREAD

**Issue by hpx7** [kriszyp/msgpackr#36]
From the docs:
> Msgpackr automatically generates record definitions that are reused and referenced by objects with the same structure. 

However I'm not sure how to get it to work using `Packr`:
```
const pakr = new Packr();
pakr.pack({foo: 0, bar: 1}); // 14 bytes
pakr.pack({foo: 2, bar: 3}); // also 14 bytes
```

If I manually provide the structures via `new Packr({structures: ["foo", "bar"]})` then the outputs are 3 bytes as expected. Is there a way to get the `Packr` to automatically infer the structures based on the inputs and apply them to subsequent encodings?

**Comment by kriszyp** [comment]
All you have to do is provide an empty structures array and it will infer the structures:
````
const myStructures = []
const pakr = new Packr({structures: myStructures});
pakr.pack({foo: 0, bar: 1}); // 3 bytes
pakr.pack({foo: 2, bar: 3}); // 3 bytes
//myStructures contains the inferred shared structures
```
Alternately, you can provide a `getStructures` and `saveStructures` which is generally more practical in applications where you need to store and retrieve inferred structures on-demand.

**Comment by hpx7** [comment]
Perfect, thank you.

How do the structures get sent over to the decoder if they aren't inside the encoded payload? The docs mention the `0x72` extension code followed by an array but I don't see that here?

**Comment by kriszyp** [comment]
There are a few different ways you can use the structures. If you are using shared structures in a database storage, the intended design is that you would store the generated structures (with saveStructures) in the database itself (or some other connected storage) and then the stored shared structures could directly loaded/read to decode the data the was encoded with those structures.

However, if you are using msgpackr to transmit data between two computers, then (like you said) the structures need to be encoded in the data that is being transmitted. In this case, the structures aren't considered "shared", but rather privately encoded. The easiest way to do this is to simply use the msgpackr streams (PackrStream and UnpackrStream), which sets up the structures, but configures the packr to treat all structures private/encoded structures and that the state of structures can be carried between messages. If you don't want to use the stream constructors, and you want to directly do this yourself, you can do it with the `sequential` flag:
```
const myStructures = []
const pakr = new Packr({structures: myStructures, sequential: true});
pakr.pack({foo: 0, bar: 1}); // 14 bytes, encodes structure
pakr.pack({foo: 2, bar: 3}); // 3 bytes
```
