### ISSUE TITLE
[TS types] Missing `read` and `write` methods in Interface `Extension` 

### ISSUE THREAD

**Issue by salortiz** [kriszyp/msgpackr#42]
While migrating my code-base, that use `addExtension` to Typescript, found that the declared `Extension` interface lacks that methods.

I solve the issue patching the declaration in [unpack.d.ts](https://github.com/kriszyp/msgpackr/blob/master/unpack.d.ts#L25) to:

```typescript
interface Extension {
	Class: Function
	type: number
	pack?(value: any): Buffer | Uint8Array
	unpack?(messagePack: Buffer | Uint8Array): any
	read?(datum: any): any
	write?(instance: any): any
}
```

**Comment by kriszyp** [comment]
Thanks for the fix! (if you have a commit on a fork, would be glad to merge/cherry-pick to give you credit for it, but if not will just commit this change)

**Comment by salortiz** [comment]
Give me a second and I'll make a PR.
Thanks.
