### ISSUE TITLE
I can't use in browser

### ISSUE THREAD

**Issue by Zaseth** [kriszyp/msgpackr#5]
I'm trying to use this library in the browser, but I can't seem to get it to work. I keep receiving the following errors:

```
Uncaught ReferenceError: exports is not defined
Uncaught ReferenceError: require is not defined
```

How do I use it in the browser? Instructions are very unclear and I can't find any CDN with usage.

**Comment by kriszyp** [comment]
Are you loading it as a plain script? If so, are you using `dist/index.js`? If you are using modules, what module loader are you using?

**Comment by Zaseth** [comment]
I tried loading it as a plain script. I see that you mention `dist/index.js`, but I can't find this in the repo.

**Comment by kriszyp** [comment]
`dist/index.js` is built and would be in the npm package, not in the repository. It should create a `msgpackr` global variable.

**Comment by Zaseth** [comment]
Thanks, it works now.

**Comment by Zaseth** [comment]
I'm still experiencing issues. I'm trying to get it to work in a client-server environment with websockets set to arraybuffer. Packing and unpacking data from the client to the server works fine, but when data is packed and sent to the client, I receive the following error message on the browser console:

```
WebSocket connection to 'ws://127.0.0.1:7070/html5' failed: Could not decode a text frame as UTF-8
```

Could you help me?
