### ISSUE TITLE
msgpackr and cbor-x .npmignore is not correct

### ISSUE THREAD

**Issue by Uzlopak** [kriszyp/msgpackr#50]
Hi kris

Just a remark: 

msgpackr and cbor-x have old .npmignore files. Your packages contain the tests and .vscode folder. 

Maybe implement the .npmignore as whitelist instead of a blacklist. 

Best regards
Uzlopak

**Comment by kriszyp** [comment]
This is a great idea, thank you for the suggestion!

**Comment by Uzlopak** [comment]
@kriszyp 

Is this solved? Can I or you close this issue?

**Comment by kriszyp** [comment]
Yes, I believe this was published in v1.5.2. Thanks again.

**Comment by Uzlopak** [comment]
No, thank you again for your great package :)
