### ISSUE TITLE
Objects are encoded as Maps

### ISSUE THREAD

**Issue by Zaseth** [kriszyp/msgpackr#6]
I'm using `pack()` server-sided to encode an object and send it to the client that decodes it the following way:

```js
new msgpackr.Packr({ useRecords: false }).unpack(new Uint8Array(message.data))
```

I have to construct and set `useRecords` because when I'm just using `unpack()`, I get Map instead of Object. Why? Can this be resolved, or allow me to just pass `useRecords` in the `unpack()` method?

**Comment by kriszyp** [comment]
The default settings for the standalone `pack` function have `useRecords` disabled and `mapsAsObjects` enabled, so if you are using that to pack, you would need this on the client side:
```
new msgpackr.Packr({ useRecords: false, mapsAsObjects: true }).unpack(new Uint8Array(message.data))
```

Or alternately, create a `Packr` instance on the server side that has `useRecords` enabled.

**Comment by Zaseth** [comment]
Would it affect performance when I construct Packr each time the client receives a message from the server?

**Comment by kriszyp** [comment]
It would certainly be faster to construct a single instance and reuse that instance (the overhead of constructing a new instance each time depends on the relative size of the objects you are deserializing).

**Comment by Zaseth** [comment]
Understandable, thank you very much for answering my questions!

**Comment by Dan-Do** [comment]
> The default settings for the standalone `pack` function have `useRecords` disabled and `mapsAsObjects` enabled, so if you are using that to pack, you would need this on the client side:
> 
> ```
> new msgpackr.Packr({ useRecords: false, mapsAsObjects: true }).unpack(new Uint8Array(message.data))
> ```
> 
> Or alternately, create a `Packr` instance on the server side that has `useRecords` enabled.

Hi @kriszyp
I am using https://github.com/crystal-community/msgpack-crystal to pack the data on server side. On client side, your library decode the Hash as Map. How to tell it decode as Object instead?
Something like `new msgpackr.unpack(new Uint8Array(data_from_server), {mapsAsObjects: true})`

**Comment by kriszyp** [comment]
@Dan-Do The default behavior of msgpackr.unpack is to decode to `Object`s. Are you asking how to do this with an `Unpackr` instance without loading the `pack` module (it should take identical parameters as a `Packr` constructor)?

**Comment by Dan-Do** [comment]
@kriszyp Never mind, I did it using Packr
```javascript
let vendor_structure = [];
let vendor_packr = new Packr({ vendor_structure, useRecords: false, mapsAsObjects: true });
vendor_packr.decode(new Uint8Array(binary_data_from_server));
```
