### ISSUE TITLE
Unpacking structures without eval

### ISSUE THREAD

**Issue by wirelyre** [kriszyp/msgpackr#60]
My environment disallows `eval` and variants. It fails to construct a function at runtime (line 444):

https://github.com/kriszyp/msgpackr/blob/3a6c46e317a2885c34da8459b2d0422af2acc434/unpack.js#L441-L455

Is there a configuration option to just use the slow path? I'd like to keep using the record extension to save space — I'm assuming it's probably still faster than decoding a regular map anyway.

**Comment by kriszyp** [comment]
Yeah, that seems reasonable to support. Would this need a configuration option, or can these be detected automatically? That is, does a test call like `new Function('')` throw an error in your environment, that can be caught to detect that eval-variants are disallowed and automatically opt of using it?

**Comment by wirelyre** [comment]
I didn't think of that!

Yes, it throws an `EvalError`, and yes, it can be caught.

**Comment by wirelyre** [comment]
Brilliant: fixed in 2c84ce6190dcae76ad4bb86dec2cbbe750467ff5, works perfectly.

Thank you so much!

**Comment by kriszyp** [comment]
Thanks for verifying. Published in v1.5.5.
