### ISSUE TITLE
Assuming global exists in unpack.js

### ISSUE THREAD

**Issue by AllNamesRTaken** [kriszyp/msgpackr#64]
The following line un unpack.js assumes node or browser.
`var glbl = typeof self == 'object' ? self : global`

Thus it cannot run on something like Clearscript V8.

Changing this to use globalThis or at least check for globalThis would solve it for those environments.

A small change for you but a huge improvement for mankind!

**Comment by kriszyp** [comment]
> A small change for you but a huge improvement for mankind!

Wow, that's the most compelling reason I have ever seen in a ticket! Publishing this right away! (Should be available in v1.6.0)
