### ISSUE TITLE
TypeError when encoding a large BigInt

### ISSUE THREAD

**Issue by mattbishop** [kriszyp/msgpackr#8]
```js
var msgpackr = require("msgpackr")
msgpackr.pack(2n**63n)
```

TypeError: Cannot convert a BigInt value to a number
    at DataView.setFloat64 (<anonymous>)
    at pack (node_modules/msgpackr/pack.js:376:17)
    at pack (node_modules/msgpackr/pack.js:309:8)
    at Object.Packr.pack.encode (node_modules/msgpackr/pack.js:102:5)

Not really sure why it's calling setFloat64 at all? If the type is bigint, the lib should just write it as-is to the targetView. If anything it should check the range to make sure the bigint is an Int64.

**Comment by Zaseth** [comment]
setBigUint64 should be used instead.

**Comment by kriszyp** [comment]
Yes, it should be using setBigInt64 for bigints that will fit and setFloat64 for larger numbers (with proper conversion), but I need to fix the thresholds and do the proper bigint to float for the larger numbers. I will get that fixed.

**Comment by mattbishop** [comment]
Actually, perhaps BigInts outside the int64 range should be rejected? https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family

Javascript bigints are not 64-bit integers, but can hold numbers of any size, including those far larger than would fit in an int64. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by kriszyp** [comment]
> Javascript bigints are not 64-bit integers
Right, that's why I was thinking with large bigints (outside of  64-bit range), the most accurate representation would be float-64. But maybe optionally throwing an error when outside range could be better than loss of precision.

**Comment by mattbishop** [comment]
My vote would be throw an out of range error.

**Comment by kriszyp** [comment]
Ok, should be fixed to handle full-range of 64-bit bigints (as int-64), throwing if out of range, with an option to serialize to float-64 (for out-of-range) if desired. Published in 1.1.2. Let me know if any issues with it.

**Comment by mattbishop** [comment]
Works well, thanks!
