### ISSUE TITLE
Does it make sense to use UnpackStream in the API service to get the request body?

### ISSUE THREAD

**Issue by budarin** [kriszyp/msgpackr#87]
I assume that the costs of creating an Unpack Stream will be much greater than the greater performance compared to unpack.

Am I wrong?

**Comment by kriszyp** [comment]
An `UnpackStream` is useful when you are transmitted multiple entities/messages over the same stream (over a period of time), so previous record definitions can be reused for subsequent entities. If you are transmitting a single entity (single top level object/array), you are right, it is faster/simpler to just use unpack.

**Comment by budarin** [comment]
thanks!
