### ISSUE TITLE
README.md#record-structure-extension-definition example doesn't work

### ISSUE THREAD

**Issue by xBZZZZ** [kriszyp/msgpackr#89]
<a href="https://github.com/kriszyp/msgpackr/blob/master/README.md#record-structure-extension-definition">README.md#record-structure-extension-definition</a> says:
<blockquote cite="https://github.com/kriszyp/msgpackr/blob/master/README.md#record-structure-extension-definition">

```
+--------+--------+--------+~~~~~~~~~~~~~~~~~~~~~~~~~+--------+--------+--------+
|  0xd4  |  0x72  |  0x40  | array: [ "foo", "bar" ] |  0x40  |  0x04  |  0x02  |
+--------+--------+--------+~~~~~~~~~~~~~~~~~~~~~~~~~+--------+--------+--------+
```
Which should generate an object that would correspond to JSON:
```js
{ "foo": 4, "bar": 2}
```
</blockquote>but example doesn't work:

```javascript
//this is in node.js
var m=require("msgpackr");
m.unpack(Buffer.of(0xD4,0x72,0x40,...m.pack(["foo","bar"]),0x40,0x04,0x02));
```
throws `Uncaught Error: Unexpected end of MessagePack data`
<div>but if you remove second <code>0x40</code> it works:

```javascript
//this is in node.js
var m=require("msgpackr");
m.unpack(Buffer.of(0xD4,0x72,0x40,...m.pack(["foo","bar"]),/*0x40, REMOVED*/0x04,0x02));
```
</div>

**Comment by kriszyp** [comment]
You are correct, thank you for pointing this!
