### ISSUE TITLE
Create stream-less module

### ISSUE THREAD

**Issue by mattbishop** [kriszyp/msgpackr#9]
I'm using msgpackr for small values and do not need the streaming capabilities. I'd like a msgpackr module that I could require() that did not export the stream module. This would simplify my webpack build and remove the unused code.

**Comment by kriszyp** [comment]
You should be able to import `msgpackr/unpack` or `msgpackr/pack` modules, which specifically do not include/export the stream module, for exactly this reason. Is that not working properly with the webpack build?

**Comment by mattbishop** [comment]
I should have clarified I'm using typescript. I have a typescript project and it won't let me do this:

```typescript
import {Unpackr} from "msgpackr/unpackr";
```

Gives me this error:

```
TS7016: Could not find a declaration file for module 'msgpackr/unpack'. '/Users/matt/Projects/Identifiers/identifiers-js/node_modules/msgpackr/unpack.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/msgpackr` if it exists or add a new declaration (.d.ts) file containing `declare module 'msgpackr/unpack';`
```

I think the project has to have typing files for unpack.js and pack.js for this to work.

I also tried using `require()` but had the same error.

**Comment by kriszyp** [comment]
I updated the type definitions in 1.1.3, let me know if this provides the right typings.

**Comment by mattbishop** [comment]
Close, it looks like exports need to be added to package.json too. I get this error now:

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './unpack' is not defined by "exports" in /Users/matt/Projects/Identifiers/identifiers-js/node_modules/msgpackr/package.json`

**Comment by kriszyp** [comment]
Does v1.1.4 work better?

**Comment by mattbishop** [comment]
That works, thanks! It generates more TS errors but I will put those into #10.
